- Cargo.toml
- src/dbus/service.rs
- src/keyring.rs
- src/portal/api/mod.rs
- src/portal/mod.rs
- src/portal/secret.rs
Fixes #9 
More loggings could be added in the future
> Add a logging feature

- Cargo.toml
See https://gitlab.gnome.org/GNOME/fractal/-/issues/1016
> Set minimal zeroize version to 1.0

- src/keyring.rs
- src/migration.rs
- src/portal/error.rs
- src/portal/secret.rs
> Fallback to host in case the portal is not available

- src/keyring.rs
- src/portal/error.rs
- src/portal/mod.rs
This feature is handy for key managers that edit entries
> portal: Add ability to modify/remove by index

- Cargo.toml
- src/portal/mod.rs
This one depends on merging #21 and #22
> portal: Spawn key derivation blocking

- src/portal/secret.rs
See https://github.com/async-rs/async-std/issues/1050
> secret: Use safe-io

- src/crypto.rs
- src/key.rs
- src/portal/api/mod.rs
- src/portal/error.rs
- src/portal/item.rs
- src/portal/mod.rs
Minima are the defaults used by libsecert.
> portal: Don't encrypt if we deem key to be weak

- src/portal/secret.rs
tokio's struct does not implement IntoRawFd.
Fixes: https://github.com/bilelmoussaoui/oo7/issues/30
> secret: Use unix::net::UnixStream

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- .github/workflows/typos.yml
- src/keyring.rs
Fixes https://github.com/bilelmoussaoui/oo7/issues/33
> keyring: Fallback to plain algorithm

- Cargo.toml
> cargo: Set msrv to 1.66

- src/dbus/service.rs
- src/keyring.rs
- src/portal/item.rs
I am not sure if adding another dependency is desired.
Its somewhat weird to return the number of seconds since the unix epoch in anything but as a date.
> Use chrono::DateTime for secrets

- client/src/dbus/api/collection.rs
- client/src/dbus/collection.rs
- client/src/dbus/item.rs
> client/dbus: Support signals in public API

- .github/workflows/CI.yml
- README.md
- cli/src/main.rs
- client/examples/basic.rs
- client/examples/basic_2.rs
- client/src/dbus/api/collection.rs
- client/src/dbus/api/item.rs
- client/src/dbus/api/prompt.rs
- client/src/dbus/api/properties.rs
- client/src/dbus/api/service.rs
- client/src/dbus/api/session.rs
- client/src/dbus/collection.rs
- client/src/dbus/item.rs
- client/src/key.rs
- client/src/keyring.rs
- client/src/lib.rs
- client/src/migration.rs
- client/src/portal/api/encrypted_item.rs
- client/src/portal/api/mod.rs
- client/src/portal/error.rs
- client/src/portal/item.rs
- client/src/portal/mod.rs
- client/src/portal/secret.rs
- portal/Cargo.toml
- portal/src/main.rs
Instead of hardcoding HashMap<&str, &str> everywhere introduce a trait that can in the future be implemented by deriving a struct for example
Helps #27
Replaces #69 
cc @zecakeh @A6GibKm
> Introduce an Attributes trait

- client/src/crypto/mod.rs
- client/src/portal/api/legacy_keyring.rs
This is the last thing in my pipeline :wink:
> client: Fix more clippy warnings

- client/src/dbus/algorithm.rs
This change implements `Serde::Deserialize` trait for `Algorithm`.
Need this change for the server side implementation.
> client: implement Deserialize for Algorithm

- client/src/crypto/mod.rs
- client/src/crypto/native.rs
- client/src/crypto/openssl.rs
- client/src/key.rs
- client/src/lib.rs
- client/src/portal/mod.rs
> client: Expose crypto module

- client/src/dbus/api/item.rs
Fixes #93
cc @haecker-felix, can you try this one?
> client/item: Force tuple usage when serializing

- client/README.md
- portal/README.md
I had a little trouble understanding what this library does and how it fits into the ecosystem. @A6GibKm explained it to me at GUADEC, so I tried to improve the documentation. I mostly tried to clarify that libsecret provides the same backends. Apart from that, these are mostly small tweaks.
> docs: rework READMEs

- portal/meson_options.txt
> portal: meson: Fix profile description

- Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
as it is much smaller and fits better the usage in the cli
> cli: Replace chrono with time

- portal/data/meson.build
- portal/data/org.freedesktop.impl.portal.desktop.oo7.service.in
- portal/meson.build
Needed to install the dbus activation file without specifiying the directory.
> portal: meson: Set fallback dbus_service_dir

- client/src/crypto/native.rs
- client/src/crypto/openssl.rs
- client/src/key.rs
Needed for the server side implementation.
> client: expose crypto::decrypt() and Key::new()

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- README.md
- server/Cargo.toml
- server/README.md
- server/src/collection.rs
- server/src/item.rs
- server/src/main.rs
- server/src/prompt.rs
- server/src/service.rs
- server/src/session.rs
This change adds the *minimal server side interface implementation of the freedesktop Secret Service API. The implementation is NOT complete. This change provides a foundation for adding further, more accurate implementations on top of it.
*minimal: Included all the Secret Service API method signatures without any implementation (todo!). Also, added a simple main().
Secret Service API spec: https://specifications.freedesktop.org/secret-service-spec/latest/
> server: adds minimal Secret Service server implementation

- server/src/main.rs
- server/src/service.rs
- server/src/service_manager.rs
- server/src/session.rs
This change implements the service method OpenSession. Also, completes the Secret Session interface implementation. And adds ServiceManager to keep track of Sessions.
> server: Implement service method OpenSession

- server/src/collection.rs
- server/src/service.rs
This change add Secret Service method SearchItems and Secret Collection method SearchItems implementation.
> server: Add SearchItems implementation

- .github/workflows/CI.yml
- server/data/meson.build
- server/data/oo7-daemon.service.in
- server/data/org.freedesktop.secrets.service.in
- server/meson.build
- server/meson_options.txt
- server/src/meson.build
> server: Add meson build support

- client/src/portal/mod.rs
Found with
cargo clippy --all-targets --workspace --all
> portal: Remove needless borrow

- Cargo.lock
- server/Cargo.toml
- server/src/collection.rs
- server/src/item.rs
- server/src/service.rs
> server: CreateItem and Delete item implementation

- Cargo.lock
- client/src/file/mod.rs
- client/src/keyring.rs
- client/src/secret.rs
- deny.toml
Fixes https://github.com/bilelmoussaoui/oo7/issues/207
cc @zecakeh
> client: Relax IncorrectSecret condition

- cli/src/main.rs
- client/src/dbus/api/secret.rs
- client/src/dbus/error.rs
- client/src/keyring.rs
Fixes https://github.com/bilelmoussaoui/oo7/issues/220
> cli: Add custom keyring file support

- server/src/collection.rs
- server/src/error.rs
- server/src/gnome/mod.rs
- server/src/gnome/prompter.rs
- server/src/item.rs
- server/src/prompt.rs
- server/src/service.rs
Split from #173 and cleaned it up further, will merge once CI passes
> Merge Prompting into main

- Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
- client/src/secret.rs
> cli: Display Examples header in bold+underline

- Cargo.toml
- client/src/crypto/native.rs
- client/src/crypto/openssl.rs
- client/src/dbus/api/collection.rs
- client/src/dbus/api/item.rs
- client/src/dbus/api/properties.rs
- client/src/dbus/api/secret.rs
- client/src/dbus/api/service.rs
- client/src/dbus/collection.rs
- client/src/dbus/item.rs
- client/src/dbus/service.rs
- client/src/file/api/attribute_value.rs
- client/src/file/api/encrypted_item.rs
- client/src/file/api/legacy_keyring.rs
- client/src/file/api/mod.rs
- client/src/file/item.rs
- client/src/file/mod.rs
- client/src/keyring.rs
- client/src/migration.rs
- portal/src/main.rs
- server/src/collection.rs
- server/src/gnome/prompter.rs
- server/src/gnome/secret_exchange.rs
- server/src/item.rs
- server/src/service.rs
- server/src/session.rs
This should be merged once 1.85 has been out for a few weeks at least.
> Port to the 2024 edition

- Cargo.lock
- Cargo.toml
- client/src/dbus/api/collection.rs
- client/src/dbus/api/item.rs
- client/src/dbus/api/prompt.rs
- client/src/dbus/api/secret.rs
- client/src/dbus/api/service.rs
- client/src/dbus/api/session.rs
- client/src/keyring.rs
- server/src/collection.rs
- server/src/main.rs
- server/src/service.rs
cc @zeenix does this look good to you? It uses https://github.com/A6GibKm/zbus/tree/add-builder-for-flags.
> server: Use connection builder

- server/src/collection.rs
- server/src/gnome/prompter.rs
- server/src/item.rs
- server/src/prompt.rs
- server/src/service.rs
- server/src/session.rs
This is a bunch of small improvements that try to improve on the ownership semantics.
> server: Improve Ownership 

- client/src/file/api/attribute_value.rs
- client/src/file/api/encrypted_item.rs
- client/src/file/item.rs
- client/src/file/mod.rs
We also add the first commit from https://github.com/bilelmoussaoui/oo7/pull/268 for no particular reason that to make it smaller.
> client: file: Add {,de}serialization test for Item
