Cargo.toml
src/keyring.rs
src/keyring/api.rs
src/lib.rs
tests/keyring.rs

The format is used by libsecret inside of flatpaks.
This patch adds a general keyring file format API
as well as convencience functions to store/lookup/delete
passwords that are encrypted via a secret from the
Secret portal.

keyring: Add support for keyring storage

---

Cargo.toml
src/helpers.rs
src/portal/api/mod.rs

We only use that for getting the xdg data dir which can be pretty easily retrieved in the platforms we care about
cc @sophie-h

portal: Drop dirs dependency

---

.github/workflows/CI.yml
.gitignore
keyring-util/Cargo.toml
keyring-util/src/main.rs
src/lib.rs

Fixes: https://github.com/bilelmoussaoui/oo7/issues/48

Add keyring-util

---

Cargo.toml
src/dbus/collection.rs
src/dbus/item.rs
src/helpers.rs
src/keyring.rs
src/portal/api/mod.rs
src/portal/mod.rs

There hasn't been updates for 1 1/2 years and it potentially pulls dependencies that are not needed.
Replace it with the maintained parts that async-std is made of.

Stop using the async-std crate

---

client/src/dbus/api/mod.rs
client/src/dbus/api/properties.rs
client/src/dbus/mod.rs

A static is like a const that can be mutated, we don't do that.

Use const rather than static for str

---

README.md
cli/src/main.rs
client/examples/basic.rs
client/examples/basic_2.rs
client/examples/dbus_service.rs
client/src/dbus/api/collection.rs
client/src/dbus/api/properties.rs
client/src/dbus/api/service.rs
client/src/dbus/collection.rs
client/src/dbus/mod.rs
client/src/keyring.rs
client/src/migration.rs
client/src/portal/api/mod.rs
client/src/portal/mod.rs

This will free us of cloning them.

Do not take ownership of the attributes

---

.github/workflows/CI.yml
.gitignore
Cargo.toml
portal/Cargo.toml
portal/data/oo7-portal.portal
portal/data/oo7-portal.service
portal/src/error.rs
portal/src/main.rs
portal/src/request.rs

There are a few things missing
This is compatible with gnome-keyring's stored secrets, but we store them with a more descriptive label, e.g.
Secret Portal token for com.belmoussaoui.ashpd.demo
See https://github.com/flatpak/xdg-desktop-portal/issues/482.

Add a portal implementation

---

client/src/portal/mod.rs

This change updates the `oo7::portal::Keyring::create_item()` to return
`oo7::portal::Item` instead of `()`
We need this change for the server side implementation. In server/daemon
side we are wrapping the return value of `create_item()` inside a struct.

portal: update create_item() to return portal::Item

---

client/src/dbus/mod.rs

We need this change for server side implementation.
See: https://github.com/bilelmoussaoui/oo7/pull/56#discussion_r1482719151

client/dbus: make Algorithm enum public under unstable feature

---

.github/workflows/docs.yml

Avoids going through the gh-pages branch, reducing the repo size

ci/docs: Use latest actions

---

client/src/portal/api/mod.rs
client/src/portal/mod.rs

This change adds `change_secret()` to `oo7::portal::Keyring` API.
`change_secret()` change/update the secret associated with a keyring.
Note: we need this change for the sever side implementation.
Fixes: #47

portal: Add rekeying support for oo7::portal::Keyring

---

client/src/portal/mod.rs

`PathBuf` has two `AsRef` implementations, so the compiler doesn't know which to choose.
We don't use `.as_ref()` instead and log the debug representation of the path, like in other places.

client: Fix compile issue with `tracing` feature

---

.github/workflows/CI.yml
.github/workflows/docs.yml
client/src/crypto/openssl.rs

Replace actions-rs actions because the [whole organization](https://github.com/actions-rs) was archived.
Add clippy checks for more client features to avoid issues like the one in #85 from making it to a release.
Needs #85 to pass CI.

ci: Replace actions-rs actions and add clippy checks for more client features

---

client/src/portal/api/legacy_keyring.rs

This looks like a test, so I assumed it's just lacking the attribute. That made my IDE complain that the function was unused.

portal: Mark test with `test` attribute

---

client/src/dbus/api/mod.rs
client/src/dbus/api/secret.rs

This change exposes `SecretInner` under unstable feature.
We need this change for the server side implementation.

client: expose SecretInner

---

client/src/keyring.rs
client/src/portal/api/mod.rs
client/src/portal/mod.rs

Instead of creating a new one because the attributes have changed.
Fixes #97.

client/item: Replace existing item in `Item::set_attributes`

---

Cargo.toml
cli/Cargo.toml
portal/Cargo.toml
portal/data/meson.build
portal/data/oo7-portal.desktop.in
portal/data/oo7-portal.portal
portal/data/oo7-portal.service
portal/data/oo7-portal.service.in
portal/data/org.freedesktop.impl.portal.desktop.oo7.service.in
portal/meson.build
portal/meson_options.txt
portal/src/main.rs
portal/src/meson.build

Temporarily disable selinux
setenforce 0
Create /run/extensions
mkdir /run/extensions
Have a preferences file `~/.config/xdg-desktop-portal/gnome-portals.conf` with contents
```
[preferred]
default=gnome;gtk;
org.freedesktop.impl.portal.Secret=oo7-portal;
```
and restart xdg-desktop-portal
```
systemctl --user restart xdg-desktop-portal
```
From oo7/portal run in a toolbox:
meson --prefix=/usr _build -Dprofile=development
ninja -C _build && DESTDIR=oo7-extension meson install -C _build
From outside the sandbox:
```
cp -r _build/oo7-extension /run/extensions/ && systemd-sysext refresh --force
```
One can get more debug output by replacing services for xdp and oo7-portals:
```
/usr/libexec/xdg-desktop-portal -r -v
```
```
RUST_LOG=oo7_portal=debug RUST_BACKTRACE=full /usr/libexec/oo7-portal …
```

portal: Add meson support

---

Cargo.lock
deny.toml
portal/Cargo.toml
portal/src/error.rs
portal/src/main.rs

Which what ends up being used by ring::rand::SecureRandom Helps get rid of some licenses & two dependencies

portal: Replace ring with getrandom

---

portal/src/main.rs

As per tokio's docs:
The caller is responsible for ensuring that the stream is in non-blocking mode. Otherwise all I/O operations on the stream will block the thread, which will cause unexpected behavior. Non-blocking mode can be set using set_nonblocking.

portal: Set nonblocking on unix stream

---

server/src/collection.rs
server/src/service.rs

This change creates and dispatches the temporary collection called session.
This collection is never stored to disk, but forgotten when the session ends.
`org.freedesktop.secrets` object tree:
```
└─ /org
└─ /org/freedesktop
└─ /org/freedesktop/secrets
└─ /org/freedesktop/secrets/collection
└─ /org/freedesktop/secrets/collection/session
```

server: Dispatch temporary session collection to the object tree

---

Cargo.lock
client/src/portal/secret.rs
server/Cargo.toml
server/src/collection.rs
server/src/error.rs
server/src/item.rs
server/src/main.rs
server/src/prompt.rs
server/src/service.rs
server/src/session.rs

Load temporary keyring when dispatching the session collection. Since the session collection is never stored to the disk, loading a temporary keyring is enough.
- And add Collection::new()
- Also store a Keyring in Collection struct.
This change loads and dispatches the login/default collection/keyring into the object tree. This change also adds,
- `--login` command line option to oo7-daemon.
- `-l, --login` option will read a password from stdin, and use it to unlock the login keyring.
- Note: currently -l option will only load the login keyring and not perform anything related to unlocking the keyring.

server: Load and dispatch login/default collection/keyring

---

server/src/collection.rs
server/src/error.rs
server/src/item.rs
server/src/service.rs
server/src/service_manager.rs

And, Collection::new() now takes an additional parameter: locked. Based on this the locked status of a collection is determined. When the daemon is executed with the -l option, default collection and its items will be in unlocked status.

server: Dispatch default collection items

---

server/src/collection.rs
server/src/item.rs
server/src/service.rs
server/src/service_manager.rs
server/src/session.rs

This change adds Secret Service method GetSecrets and Secret Item methods GetSecret and SetSecret.

server: Add GetSecret, GetSecrets and SetSecret implementation

---

server/src/collection.rs
server/src/item.rs
server/src/service.rs
server/src/service_manager.rs
server/src/session.rs

server: Add service method Lock and Unlock implementation

---

client/src/crypto/error.rs
client/src/crypto/mod.rs
client/src/crypto/native.rs
client/src/crypto/openssl.rs
client/src/dbus/api/secret.rs
client/src/dbus/collection.rs
client/src/dbus/error.rs
client/src/dbus/item.rs
client/src/dbus/service.rs
client/src/file/api/attribute_value.rs
client/src/file/api/encrypted_item.rs
client/src/file/api/legacy_keyring.rs
client/src/file/api/mod.rs
client/src/file/error.rs
client/src/file/item.rs
client/src/file/mod.rs
client/src/key.rs
client/src/keyring.rs
client/src/lib.rs
server/src/collection.rs
server/src/item.rs
server/src/service.rs

client: Don't panic if a cryptography operation fails

---

Cargo.toml
cli/Cargo.toml
client/src/dbus/api/collection.rs
client/src/dbus/api/item.rs
client/src/dbus/api/service.rs
portal/Cargo.toml
server/Cargo.toml

This is to stop oo7/native_crypto feature being enabled when using oo7/openssl_crypto on the server side (or the opposite).
This also resolves the following error when setting oo7 `default-features = false` in workspace members.
"`default-features` is ignored for oo7, since `default-features` was not specified for `workspace.dependencies.oo7`, this could become a hard error in the future".

Disable oo7 default-features in workspace.dependencies

---

server/src/collection.rs

Change attribute comparison to match on lookups where the search attributes form a subset of the item's attributes.
Fixes #233

server: match items if search attributes are a subset

---

cli/src/main.rs
client/src/dbus/api/secret.rs
client/src/file/api/legacy_keyring.rs
client/src/file/api/mod.rs
client/src/file/item.rs
client/src/file/mod.rs
client/src/keyring.rs
client/src/lib.rs
client/src/secret.rs

Closes <https://github.com/bilelmoussaoui/oo7/issues/170>

client: Manually add a content-type attribute

---

server/data/oo7-daemon.service.in

The unit file is a user unit file. This means that it will automatically fail (with code 218) when started with either the CapabilityBoundingSet or AmbientCapabilities properties. This can be tested by running any of:
```
systemd-run --pipe --wait --user --property CapabilityBoundingSet=CAP_IPC_LOCK echo 1
systemd-run --pipe --wait --user --property AmbientCapabilities=CAP_IPC_LOCK echo 1
```

daemon: Do not restrict caps on unit file

---

server/src/service.rs

This was a bit too spammy. Another option would be to keep a hashmap of already resolved collections to only print this once per alias, but it seems like too much work and a waste of memory.

server: Demote info! to debug!

---

client/src/file/api/attribute_value.rs
client/src/file/item.rs
client/src/lib.rs

A mac does not contain sensitive data (no more than a hash at least), it does not need zeroizing on drop.

client: Stop giving mac as Zeroizing

---

server/src/service.rs

For some reason, even though the call to `Service.connection.set()` succeeds, afterwards calls to `Service.connection.get()` always return None.
This fixes this issue.

service: Refactor connection build and service.collection field set
